# Generated by Django 3.1.1 on 2020-10-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grup',
            table='group',
        ),
    ]
