# Generated by Django 3.1.1 on 2020-10-05 04:05

from django.db import migrations, models
import pesan.enums


class Migration(migrations.Migration):

    dependencies = [
        ('pesan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.IntegerField(null=True)),
                ('is_group', models.CharField(choices=[(pesan.enums.IsEnum['Y'], 'Y'), (pesan.enums.IsEnum['N'], 'N')], max_length=3, null=True)),
                ('group_name', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('is_reply', models.CharField(choices=[(pesan.enums.IsEnum['Y'], 'Y'), (pesan.enums.IsEnum['N'], 'N')], max_length=3, null=True)),
                ('content_type', models.CharField(choices=[(pesan.enums.IsEnum['Y'], 'Y'), (pesan.enums.IsEnum['N'], 'N')], max_length=10, null=True)),
                ('content_location', models.TextField()),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('processed', models.CharField(choices=[(pesan.enums.IsEnum['Y'], 'Y'), (pesan.enums.IsEnum['N'], 'N')], max_length=3, null=True)),
                ('processed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('contact_parser', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
