# Generated by Django 3.1.1 on 2020-10-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesan', '0002_outbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='content_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
