# Generated by Django 3.1.1 on 2020-10-12 05:58

from django.db import migrations, models
import pesan.enums


class Migration(migrations.Migration):

    dependencies = [
        ('pesan', '0003_auto_20201005_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='content_type',
            field=models.CharField(choices=[(pesan.enums.IsEnum['Y'], 'Y'), (pesan.enums.IsEnum['N'], 'N')], default='Text', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='is_group',
            field=models.CharField(choices=[(pesan.enums.IsEnum['Y'], 'Y'), (pesan.enums.IsEnum['N'], 'N')], default='N', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='is_reply',
            field=models.CharField(choices=[(pesan.enums.IsEnum['Y'], 'Y'), (pesan.enums.IsEnum['N'], 'N')], default='N', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='machine_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='processed',
            field=models.CharField(choices=[(pesan.enums.IsEnum['Y'], 'Y'), (pesan.enums.IsEnum['N'], 'N')], default='N', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
