# Generated by Django 3.1.1 on 2020-10-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesan', '0004_auto_20201012_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='machine_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
