# Generated by Django 3.1.1 on 2020-10-15 07:19

from django.db import migrations, models
import pesan.enums


class Migration(migrations.Migration):

    dependencies = [
        ('pesan', '0006_auto_20201013_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbox',
            name='desa_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outbox',
            name='title_message',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='is_group',
            field=models.CharField(choices=[(pesan.enums.IsEnum['Y'], 'Y'), (pesan.enums.IsEnum['N'], 'N')], default='Y', max_length=3, null=True),
        ),
    ]
