# Generated by Django 3.1.1 on 2020-10-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('is_active', models.IntegerField(max_length=11)),
                ('is_tester', models.IntegerField(max_length=11)),
            ],
        ),
    ]
