# Generated by Django 3.1.1 on 2020-10-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontak', '0002_auto_20201001_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='is_active',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='is_tester',
            field=models.IntegerField(),
        ),
    ]
