# Generated by Django 3.1.1 on 2020-10-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grup', '0001_initial'),
        ('kontak', '0003_auto_20201001_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grup.grup'),
        ),
    ]
