# Generated by Django 3.1.1 on 2020-10-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontak', '0004_auto_20201002_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='is_tester',
            field=models.IntegerField(default=0),
        ),
    ]
