# Generated by Django 3.1.1 on 2020-10-09 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desa', '0001_initial'),
        ('kontak', '0005_auto_20201008_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='desa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='desa.desa'),
        ),
    ]
