# Generated by Django 3.1.1 on 2020-10-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontak', '0006_contacts_desa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacts',
            table='contacts',
        ),
    ]
